# Generated by Django 3.0.6 on 2020-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('orgs', '0001_initial'), ('orgs', '0002_auto_20200520_2253'), ('orgs', '0003_auto_20200521_0115'), ('orgs', '0004_org_slug'), ('orgs', '0005_auto_20200522_0144')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ngo_name', models.CharField(max_length=100)),
                ('ketto_link', models.URLField(max_length=300)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_image_link', models.URLField(blank=True, max_length=300, null=True)),
                ('ngo_image', models.ImageField(blank=True, null=True, upload_to='ngo_images/')),
                ('ngo_image_link', models.URLField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('ngo_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('ngo_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ngo_location', models.CharField(blank=True, max_length=100, null=True)),
                ('ngo_website', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
